#!/usr/bin/env ruby

require 'rubygems'
require 'soundcloud'
require_relative '../../util/routing/routing'

module SoundCloudTrack
	def self.enqueue(id)
		client = Soundcloud.new(client_id: '4a4922f76dab4f90e757b13b67e29222')
		track = client.get("/tracks/#{id}")
		stream_url = client.get(track.stream_url, allow_redirects: true)
		Process.wait spawn(
			"util/player",
			"enqueue",
			"-t","title=#{track.title}",
			"-t","artist=#{track.user.username}",
			"-t","description=#{track.description}",
			"-t","duration=#{track.duration / 1000}",
			stream_url.location)
	end
end

Routing::route do |r|
	r.enqueue [:id] { |b| SoundCloudTrack::enqueue b[:id].to_i }
end
