#!/usr/bin/env ruby

require 'rubygems'
require_relative '../../util/soundcloud/soundcloud_api'
require_relative '../../util/routing/routing'

puts 'application/json'

module SoundCloudTrack
	def self.enqueue(id)
		client = SoundcloudAPI::create
		track = client.get("/tracks/#{id}")
		begin
			stream_url = client.get(track.stream_url, {}, follow_redirects: false)
		rescue SoundCloud::ResponseError => e
			Process.wait spawn(
				"util/enqueuedownload",
				e.response["location"],
				"--fingerprint",
				"-t","title=#{track.title}",
				"-t","artist=#{track.user.username}",
				"-t","description=#{track.description}",
				"-t","duration=#{track.duration / 1000}")
		end
	end
end

Routing::route do |r|
	r.enqueue [:id] { |b| SoundCloudTrack::enqueue b[:id].to_i }
end
