#!/bin/bash

echo 'Installing wget'
sudo apt-get install wget

echo 'Installing python 2.7'
sudo apt-get install python2.7 python2.7-dev libimage-exiftool-perl

echo 'Checking if pip is installed'
if ! pip-2.7 > /dev/null; then
	tmpdir='/var/tmp/pipinstall'

	echo 'No. Installing pip'
	echo "Working dir: $tmpdir"
	mkdir "$tmpdir"
	pushd "$tmpdir"

	wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
	sudo python2.7 ez_setup.py

	wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
	sudo python2.7 get-pip.py

	popd
	sudo rm -rf "$tmpdir"
else
	echo 'Yes. continuing'
fi

echo 'Installing twisted'
sudo pip-2.7 install twisted

echo 'Installing colorama'
sudo pip-2.7 install colorama

echo 'Installing pyALSA'
tmpdir='/var/tmp/pyalsainstall'
echo "Working dir: $tmpdir"
sudo apt-get install libasound2-dev

mkdir "$tmpdir"
pushd "$tmpdir"
wget ftp://ftp.alsa-project.org/pub/pyalsa/pyalsa-1.0.26.tar.bz2
tar xjvf pyalsa-1.0.26.tar.bz2
cd pyalsa-1.0.26
python2.7 setup.py build
sudo python2.7 setup.py install
popd
sudo rm -rf "$tmpdir"
