#!/bin/bash

echo "$HOME"

# Load RVM into a shell session *as a function*
#if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
#
#  # First try to load from a user install
#  source "$HOME/.rvm/scripts/rvm"
#
#elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
#
#  # Then try to load from a root install
#  source "/usr/local/rvm/scripts/rvm"
#
#fi
#
#rvm list
#

script="$1"
shift
"$script" "$@"


