#!/usr/bin/env ruby

require 'securerandom'
require_relative 'routing/routing'

##
# Provides methods to manipulate the on-disk media cache
module Cache
	##
	# Create a new file with a unique name and returns its name
	def self.reserve_file
		uuid = SecureRandom.uuid
		`touch tmp/cache/#{uuid}`
		uuid
	end

	##
	# Clears the entire cache
	def self.cleanup
		`rm tmp/cache/*`
	end

	##
	# Remove a specific +file+ from the cache
	def self.remove_file(file)
		`rm tmp/cache/#{file}`
	end
end

Routing::route ARGV do |r|
	r.reserve_file { puts Cache::reserve_file }
	r.cleanup { Cache::cleanup }
	r.remove_file [:file], file: /[0-9a-f-]+/ do
		Cache::remove_file b[:file]
	end
end