#!/bin/bash

if [[ "$1" == "--here" ]]; then
	shift

	# Download, direct output to a cached enqueuer.
	# Run in background to return immediately.
	curl "$uri" | "$util/enqueuecached" "$@" &
else
	"$0" "--here" "$@" & disown
fi
