#!/usr/bin/env ruby
require 'drb/drb'
require 'optparse'

DRb.start_service

player = DRbObject.new_with_uri("drbunix:/var/tmp/imp-player.socket")

OptionParser.new do |opts|
	opts.on("--play PATH") do |path|
		puts "Uw client heeft et ontvangen, ge wilt spelen #{path}"
		player.play(path)
	end

	opts.on("--stop") do 
		player.stop
	end

	opts.on("--pause") do
		player.pause
	end

	opts.on("--is_playing") do
		puts player.is_playing?
	end

	opts.on("--get_title") do
		player.get_title
	end

	opts.on("--get_time") do
		player.get_time
	end

	opts.on("--get_length") do
		player.get_length
	end

	opts.on("--seek SECONDS") do |seconds|
		player.seek(seconds)
	end
	
	opts.on("--volume X") do |x|
		player.volume(x)
	end

	opts.on("--skip") do
		player.skip
	end

	opts.on("--flush") do
		player.flush
	end

	opts.on("--magic_shuffle X") do |x|
		player.magic_shuffle(x)
	end

	opts.on("--shuffle") do 
		player.shuffle
	end

	opts.on("--dequeue ITEM") do |item|
		player.dequeue(item)
	end

	opts.on("--playlist") do
		player.playlist
	end
	
	opts.on("--history") do
		player.history
	end

	opts.on("--previous") do
		player.previous
	end

	opts.on("--replay") do
		player.replay
	end

	opts.on("--enqueue ITEM") do |item|
		player.enqueue(item)
	end
end.parse!

