#!/usr/bin/env ruby

puts "text/plain"

require 'rubygems'
require 'grooveshark'
require 'optparse'
require_relative '../../util/routing/routing'

@client = Grooveshark::Client.new
session = @client.session
begin 
	user = @client.login('ayrton@infogroep.be','$Hrubb3rY')
rescue Grooveshark::InvalidAuthentication
	puts "Ooops! Wrong username or password"
end

def play_playlist(id)
	playlist = Grooveshark::Playlist.new(@client,{'playlist_id' => id })#user.get_playlist(84280827)
	playlist.load_songs
	songs = playlist.songs
	
	#song = songs.first
	songs.each do |song|
		url = @client.get_song_url(song)
		puts url
		spawn('util/player','--enqueue',url)
	end
	spawn('util/player','--skip')
end

#play_playlist(84280827)

Routing::route do |r|
	r.play [:playlist_id] { |b| play_playlist b[:playlist_id].to_i }
end

