#!/usr/bin/env ruby

puts "application/json"

require 'rubygems'
require 'grooveshark'
require 'optparse'
require_relative '../../util/routing/routing'

@client = Grooveshark::Client.new
session = @client.session

##
# Part of the /grooveshark/playlists script.
# Provides an interface to queue grooveshark playlists
module GroovesharkPlaylists
	##
	# Add an entire playlist to the the queue
	def play_playlist(id)
		playlist = Grooveshark::Playlist.new(@client,{'playlist_id' => id })#user.get_playlist(84280827)
		playlist.load_songs
		songs = playlist.songs
		
		#song = songs.first
		songs.each do |song|
			url = @client.get_song_url(song)
			Process.wait spawn('util/enqueuehttp',url)
		end
		Process.wait spawn('util/player','skip')
	end
end

#play_playlist(84280827)


Routing::route do |r|
	r.play [:playlist_id] { |b| GroovesharkPlaylists::play_playlist b[:playlist_id].to_i }
end

