#!/usr/bin/env ruby

puts "text/plain"
require 'optparse'
require_relative '../../util/routing/routing'

##
# Part of the /control/current script.
# Provides an interface to manipulate the currently playing media.
module Current
	##
	# Pause the current media
	def self.pause
		puts "Pause!"
		spawn('util/player','pause')
	end

	##
	# Stop the current media
	def self.stop
		puts "Stop!"
		spawn('util/player','stop')
	end

	##
	# Skip the current media
	def self.next
		puts "Next!"
		spawn('util/player','next')
	end

	##
	# Play the previous media
	def self.previous
		puts "Previous!"
		spawn('util/player','previous')
	end

	##
	# Restart the current song from the beginning
	def self.replay
		puts "Replay!"
		spawn('util/player', 'replay')
	end
end

Routing::route do |r|
	r.pause { Current::pause }
	r.stop { Current::stop }
	r.next { Current::next }
	r.previous { Current::previous }
	r.replay { Current::replay }
end