#!/usr/bin/env ruby

puts "text/plain"
require 'optparse'
require_relative '../../util/routing/routing'

##
# Part of the /control/current script.
# Provides an interface to manipulate the currently playing media.
module Current
	##
	# Pause the current media
	def self.pause
		puts "Pause!"
		Process.wait spawn('util/player','pause')
	end

	##
	# Stop the current media
	def self.stop
		puts "Stop!"
		Process.wait spawn('util/player','stop')
	end

	##
	# Skip the current media
	def self.next
		puts "Next!"
		Process.wait spawn('util/player','next')
	end

	##
	# Play the previous media
	def self.previous
		puts "Previous!"
		Process.wait spawn('util/player','previous')
	end

	##
	# Restart the current song from the beginning
	def self.replay
		puts "Replay!"
		Process.wait spawn('util/player', 'replay')
	end

	##
	# Gets the current time in seconds
	def self.get_time
		Process.wait spawn('util/player','get_time')
	end

	##
	# Sets the current time in seconds
	def self.seek time
		Process.wait spawn('util/player','seek',time)
	end

	##
	# Get the total length in seconds
	def self.get_length
		Process.wait spawn('util/player','get_length')
	end
end

Routing::route do |r|
	r.pause { Current::pause }
	r.stop { Current::stop }
	r.next { Current::next }
	r.previous { Current::previous }
	r.replay { Current::replay }
	r.get ['time'] { Current::get_time }
	r.put ['time',:time] { |b| Current::seek b[:time] }
	r.get ['length'] { Current::get_length }
end