# Seeds

include Favorites::Favorites

Favorite.create!({ name: 'VRT Radio 1', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtradio1-high.m3u' } })
Favorite.create!({ name: 'VRT Radio 2 Antwerpen', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtra2ant-high.m3u' } })
Favorite.create!({ name: 'VRT Radio 2 Limburg', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtra2lim-high.m3u' } })
Favorite.create!({ name: 'VRT Radio 2 Oost-Vlaanderen', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtra2ovl-high.m3u' } })
Favorite.create!({ name: 'VRT Radio 2 Vlaams-Brabant', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtra2vlb-high.m3u' } })
Favorite.create!({ name: 'VRT Radio 2 West-Vlaanderen', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtra2wvl-high.m3u' } })
Favorite.create!({ name: 'VRT Radio Klara', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtklara-high.m3u' } })
Favorite.create!({ name: 'VRT Klara Continuo', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtklaracontinuo-high.m3u' } })
Favorite.create!({ name: 'VRT MNM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtmnm-high.m3u' } })
Favorite.create!({ name: 'VRT MNM Hits', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtmnmhits-high.m3u' } })
Favorite.create!({ name: 'VRT Studio Brussel', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtstubru-high.m3u' } })
Favorite.create!({ name: 'VRT Sporza', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtsporza-high.m3u' } })
Favorite.create!({ name: 'VRT Ketnet Radio', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.listenlive.eu/vrtketnet-high.m3u' } })
Favorite.create!({ name: 'Accent FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://server-06.stream-server.nl:8628/listen.pls' } })
Favorite.create!({ name: 'Antwerpen fm', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://streams.lazernet.be:2710/listen.pls' } })
Favorite.create!({ name: 'City Music', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://shoutcast01.edpnet.net:10150/listen.pls' } })
Favorite.create!({ name: 'Club FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stream.publimediasvr.be/playlist_club.m3u' } })
Favorite.create!({ name: 'Crooze.fm', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://193.227.114.74:9000/listen.pls' } })
Favorite.create!({ name: 'Family Radio', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stream.publimediasvr.be:8000/family.mp3.m3u' } })
Favorite.create!({ name: 'FM Brussel', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://ice2.sz.xlcdn.com:8000/sz=fmbrussel=fmb988.mp3.m3u' } })
Favorite.create!({ name: 'FM Goud', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stream01.level27.be:8008/listen.pls' } })
Favorite.create!({ name: 'Geel FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://geelfm.dyndns.org:8000/geelfm.m3u' } })
Favorite.create!({ name: 'Goldies Radio', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.goldiesradio.be/live/playlist.pls' } })
Favorite.create!({ name: 'GRK', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://radiogrk.shoutcaststream.com/stream.m3u' } })
Favorite.create!({ name: 'Halse Radio Victoria', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://livestream.radiovictoria.be/tijr.m3u' } })
Favorite.create!({ name: 'Hit FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://94.23.48.124:8000/listen.pls' } })
Favorite.create!({ name: 'HUMORzender', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.humorzender.be/streams/winamp.pls' } })
Favorite.create!({ name: 'Joe FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://apps.joe.be/asx/joe_hi.asx' } })
Favorite.create!({ name: 'Jouw! Radio', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.jouwradio.be/stream/jouwradio_128.pls' } })
Favorite.create!({ name: 'Komilfoo FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://shoutcast01.edpnet.net:10130/listen.pls' } })
Favorite.create!({ name: 'M.i.G', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stream.intronic.nl/radiomig.m3u' } })
Favorite.create!({ name: 'Molenland FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://streams.movemedia.eu:8550/listen.pls' } })
Favorite.create!({ name: 'Nostalgie', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://nostalgiewhatafeeling.ice.infomaniak.ch/nostalgiewhatafeeling-128.mp3.m3u' } })
Favorite.create!({ name: 'Q-Music', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://mp3streaming.q-music.be/QBE_MP3_HI.m3u' } })
Favorite.create!({ name: 'Radio Benelux', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stream20.level27.be:11030/listen.pls' } })
Favorite.create!({ name: 'Radio BRO', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.movemedia.be/stream.php?port=8410&ext=pls' } })
Favorite.create!({ name: 'Radio Brouwer', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://server-16.stream-server.nl:8434/listen.pls' } })
Favorite.create!({ name: 'Radio Centraal', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.radiocentraal.org/stream/centraal.pls' } })
Favorite.create!({ name: 'Radio Diest', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://streams.lazernet.be:3790/listen.pls' } })
Favorite.create!({ name: 'Radio Extra Gold', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://streaming.radioextragold.be:8050/listen.pls' } })
Favorite.create!({ name: 'Radio FG', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://radiofg.impek.com/fga64.aac.m3u' } })
Favorite.create!({ name: 'Radio Ham', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://50.7.234.130:8258/listen.pls' } })
Favorite.create!({ name: 'Radio IRO', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stadsradio-iro.be:3001/listen.pls' } })
Favorite.create!({ name: 'Radio Katanga', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.katanga.be/streamplayer/externalplayers/playlist.pls' } })
Favorite.create!({ name: 'Radio Land Van Waas', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://62.75.228.171:8066/listen.pls' } })
Favorite.create!({ name: 'Radio Lichtaart', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://radiolichtaart.shoutcaststream.com/stream.m3u' } })
Favorite.create!({ name: 'Radio Lorali', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://lorali.shoutcaststream.com/stream.m3u' } })
Favorite.create!({ name: 'Radio Maria', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stream.radiomaria.be/RadioMaria-96.pls' } })
Favorite.create!({ name: 'Radio Minerva', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.radio-minerva.be/stream.php?ext=pls' } })
Favorite.create!({ name: 'Radio Mol', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://studio.radiomol.be:5001/listen.pls' } })
Favorite.create!({ name: 'Radio Monza', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stream.intronic.nl/radiomonza.m3u' } })
Favorite.create!({ name: 'Radio Opsinjoor', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.opsinjoor.be/stream.php?ext=pls' } })
Favorite.create!({ name: 'Radio Paradijs', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://86.39.163.54:8000/listen.pls' } })
Favorite.create!({ name: 'Radio PROS', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://streams.lazernet.be:3180/listen.pls' } })
Favorite.create!({ name: 'Radio Reflex', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://streams.lazernet.be:3400/listen.pls' } })
Favorite.create!({ name: 'Radio Scorpio', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://193.190.253.57:8000/stream.m3u' } })
Favorite.create!({ name: 'Radio Spes', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.itaf.be/radiospes/radiospes.m3u' } })
Favorite.create!({ name: 'Radio Stad', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://193.227.114.74:8002/listen.pls' } })
Favorite.create!({ name: 'Radio Star', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://staronline.no-ip.biz:8000/listen.pls' } })
Favorite.create!({ name: 'Radio Tequila', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://radiotequila.homeip.net:8000/listen.pls' } })
Favorite.create!({ name: 'Radio Utopia', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://radioutopia.shoutcaststream.com/stream.m3u' } })
Favorite.create!({ name: 'Radio Victoria', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://livestream.radiovictoria.be/tijr.m3u' } })
Favorite.create!({ name: 'Radio VRW', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.movemedia.be/stream.php?port=8560&ext=pls' } })
Favorite.create!({ name: 'RGR FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.rgrfm.be/rgr1281.pls' } })
Favorite.create!({ name: 'Roots Radio', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://army.wavestreamer.com:4947/listen.pls' } })
Favorite.create!({ name: 'Spits FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.spits.fm/live.pls' } })
Favorite.create!({ name: 'Stadsradio Halle', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stadsradio.open2.be/stream/stadsradio.pls' } })
Favorite.create!({ name: 'Tempo FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://mirror1.livestream.tempo.fm/tempofm' } })
Favorite.create!({ name: 'Top Radio', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://ns24907.ovh.net:8000/listen.pls' } })
Favorite.create!({ name: 'Topradio Aalter', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.topradioaalter.be/interactive/livestream_aac.m3u' } })
Favorite.create!({ name: 'Trendy FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.trendyfm.be/stream/trendystream.pls' } })
Favorite.create!({ name: 'Trudo FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://cp7.shoutcheap.com:2199/tunein/trudofm.pls' } })
Favorite.create!({ name: 'URGent Radio', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://urgent.stream.flumotion.com/urgent/high.ogg.m3u' } })
Favorite.create!({ name: 'VBRO', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://vbro.live-streams.nl:8005/listen.pls' } })
Favorite.create!({ name: 'Viva FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://stream12.fluoline.net:8000/listen.pls' } })
Favorite.create!({ name: 'Webradio Golden Flash', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.goldenflash.org/servers/winamp128.pls' } })
Favorite.create!({ name: 'Zen FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://ns25042.ovh.net:8010/listen.pls' } })
Favorite.create!({ name: 'Zoe FM', user: 'ig', is_public: true, keywords: '', plugin: 'stream', options: { uri: 'http://www.zoe.fm/stream.php?ext=pls' } })
