#!/usr/bin/env ruby

require 'json'
require 'optparse'
require_relative '../../util/routing/routing'

module Queue
	def self.queue
		spawn('util/player','playlist')
	end

	#TODO
	def self.enqueue
		#Add an item to the queue
	end

	def self.get_item(id)
		spawn('util/player', 'find_media', id)
	end

	def self.shuffle
		spawn('util/player', 'shuffle')
	end

	def self.magic_shuffle
		re = RegExp.new(JSON.parse(gets))
		queue = JSON.parse(`util/player playlist`)
		`util/player shuffle`
		queue.each do |media|
			media[:info].each do |k,v|
				if re.match(v)
					`util/player to_front #{media[:id]}`
					break
				end
			end
		end
	end

	def self.magic_shuffle(id)
		spawn('util/player', 'magic_shuffle' id)
	end

	def self.delete
		ids = JSON.parse(gets)
		ids.each { |id| wait spawn('util/player','dequeue',id) }
	end

	def self.delete(id)
		spawn('util/player', 'dequeue', id)
	end

	def self.delete_regex
		re = RegExp.new(JSON.parse(gets))
		queue = JSON.parse(`util/player playlist`)
		queue.each do |media|
			media[:info].each do |k,v|
				if re.match(v)
					`util/player dequeue #{media[:id]}`
					break
				end
			end
		end
	end

	def self.to_front
		re = RegExp.new(JSON.parse(gets))
		queue = JSON.parse(`util/player playlist`)
		queue.each do |media|
			media[:info].each do |k,v|
				if re.match(v)
					`util/player to_front #{media[:id]}`
					break
				end
			end
		end
	end

	def self.to_front(id)
		spawn('util/player', 'to_front', id)
	end

	def self.enqueue_to_front(id)
		class.enqueue(id)
		class.to_front(id)
	end
end

Routing::route do |r|
	r.get { Queue::queue }
	r.get [:id] { |b| Queue::get_item b[:id] } 
	r.post [:item] { |b| Queue::enqueue b[:id]}
	r.shuffle { Queue::shuffle }
	r.magic_shuffle { Queue::magic_shuffle }
	r.magic_shuffle [:id] { |b| Queue::magic_shuffle b[:id] }
	r.delete { Queue::delete }
	r.delete [:id] { |b| Queue::delete b[:id] }
	r.delete_regex { Queue::delete_regex }
	r.to_front { Queue::to_front }
	r.to_front [:id] { |b| Queue::to_front b[:id] }
	r.enqueue_to_front [:id] { |b| Queue::enqueue_to_front b[:id] }

end