#!/bin/bash

buffer_size=100000

echo 'application/json'
file="tmp/cache/$(util/cache reserve_file)"
id=""

{
	while [[ $(stat -c %s "$file") < $buffer_size ]]; do
		sleep 0.5
	done
	id="$(util/player enqueue --fingerprint "$file")"
} &

cat > "$file"
if [[ ! -z "$id" ]]; then
	util/player reevaluate --fingerprint "$id"
fi
